-- JSHS-WIKI Supabase schema
-- Supabase SQL Editor에서 전체 실행하세요.

create or replace function public.is_jshs_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (auth.jwt() ->> 'email') ilike '%@jeju-s.jje.hs.kr',
    false
  );
$$;

create table if not exists public."Articles" (
  id bigint generated by default as identity primary key,
  title text not null unique,
  content text not null default '',
  category text not null default 'general',
  updated_at timestamptz not null default now()
);

create table if not exists public."Revisions" (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public."Articles"(id) on delete cascade,
  prev_content text not null default '',
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  edit_summary text not null default '',
  editor_nickname text not null default '',
  editor_gen text not null default ''
);

create table if not exists public."Generations" (
  id bigint generated by default as identity primary key,
  gen_number integer not null unique,
  slogan text not null default '',
  rep_image text not null default ''
);

create table if not exists public."Archives" (
  id bigint generated by default as identity primary key,
  gen_id bigint not null references public."Generations"(id) on delete cascade,
  title text not null,
  category text not null default 'archive',
  file_url text not null default ''
);

create index if not exists articles_title_idx on public."Articles"(title);
create index if not exists revisions_article_id_idx on public."Revisions"(article_id);
create index if not exists archives_gen_id_idx on public."Archives"(gen_id);

alter table public."Articles" enable row level security;
alter table public."Revisions" enable row level security;
alter table public."Generations" enable row level security;
alter table public."Archives" enable row level security;

drop policy if exists "articles_select_public" on public."Articles";
create policy "articles_select_public"
  on public."Articles" for select
  using (true);

drop policy if exists "articles_insert_jsh" on public."Articles";
create policy "articles_insert_jsh"
  on public."Articles" for insert
  with check (public.is_jshs_editor());

drop policy if exists "articles_update_jsh" on public."Articles";
create policy "articles_update_jsh"
  on public."Articles" for update
  using (public.is_jshs_editor())
  with check (public.is_jshs_editor());

drop policy if exists "revisions_select_public" on public."Revisions";
create policy "revisions_select_public"
  on public."Revisions" for select
  using (true);

drop policy if exists "revisions_insert_jsh" on public."Revisions";
create policy "revisions_insert_jsh"
  on public."Revisions" for insert
  with check (public.is_jshs_editor());

drop policy if exists "generations_select_public" on public."Generations";
create policy "generations_select_public"
  on public."Generations" for select
  using (true);

drop policy if exists "generations_write_jsh" on public."Generations";
create policy "generations_write_jsh"
  on public."Generations" for all
  using (public.is_jshs_editor())
  with check (public.is_jshs_editor());

drop policy if exists "archives_select_public" on public."Archives";
create policy "archives_select_public"
  on public."Archives" for select
  using (true);

drop policy if exists "archives_insert_jsh" on public."Archives";
create policy "archives_insert_jsh"
  on public."Archives" for insert
  with check (public.is_jshs_editor());

drop policy if exists "archives_update_jsh" on public."Archives";
create policy "archives_update_jsh"
  on public."Archives" for update
  using (public.is_jshs_editor())
  with check (public.is_jshs_editor());

insert into public."Generations" (gen_number, slogan, rep_image)
values
  (28, '함께 성장하는 과학도', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&h=400&fit=crop'),
  (27, '끝없는 호기심으로', 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=400&fit=crop')
on conflict (gen_number) do nothing;
